spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://stormy-citadel-28405.herokuapp.com/eureka}
  instance:
    preferIpAddress: false